import React, { createContext, useContext, useState } from 'react';

export type LanguageCode = 'hi' | 'en' | 'mr' | 'gu' | 'te';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  hi: {
    appName: 'कृषि सारथी',
    networkTitle: 'सहकारी कृषि आसूचना नेटवर्क',
    tagline: 'उपग्रह आसूचना से किसान क्रियान्वयन तक',
    markField: 'अपना खेत चिह्नित करें',
    satelliteIntelligence: 'उपग्रह आसूचना',
    weatherIntelligence: 'मौसम आसूचना',
    soilIntelligence: 'मृदा आसूचना',
    cropRecommendation: 'फसल अनुशंसा इंजन',
    cropDoctor: 'फसल रोग निदान',
    aiCopilot: 'कृषि सारथी AI सलाहकार',
    stateCooperation: 'राज्य सहयोग नेटवर्क',
    liveTelemetry: 'सक्रिय उपग्रह टेलीमेट्री',
    demoMode: 'सत्यापित डेमो डेटा',
    healthyStatus: 'स्वस्थ वनस्पति',
    moderateStress: 'मध्यम तनाव',
    degradedStatus: 'गंभीर गिरावट',
    highRisk: 'उच्च जोखिम',
    mediumRisk: 'मध्यम जोखिम',
    lowRisk: 'कम जोखिम',
    rainfallWarning: '72 घंटों में 62 mm भारी वर्षा का अनुमान',
    postponeIrrigation: 'सिंचाई और कीटनाशक छिड़काव स्थगित रखें',
    suitabilityScore: 'उपयुक्तता स्कोर',
    whyThisCrop: 'यह फसल क्यों?',
    soilSuitability: 'मृदा उपयुक्तता',
    rainfallSuitability: 'वर्षा अनुकूलता',
    tempSuitability: 'तापमान उपयुक्तता',
    waterMatch: 'जल आवश्यकता मेल',
    satelliteCondition: 'उपग्रह वनस्पति स्थिति',
    askQuestionPlaceholder: 'कृषि सारथी से अपने खेत या फसल के बारे में पूछें...',
    send: 'पूछें',
    quickQuestions: 'त्वरित प्रश्न',
    q1: 'मेरे खेत में फसल की स्थिति कैसी है?',
    q2: 'क्या अगले 3 दिन में सिंचाई करनी चाहिए?',
    q3: 'सोयाबीन के बाद कौन सी फसल सबसे उपयुक्त है?',
    diagnoseTitle: 'पत्ती का फोटो अपलोड करें या नमूना चुनें',
    severity: 'गंभीरता',
    confidence: 'सटीकता',
    disclaimer: 'यह निदान AI अनुमान पर आधारित है। कृपया स्थानीय कृषि विज्ञान केंद्र (KVK) से परामर्श लें।',
    switchField: 'खेत बदलें',
    registerModel: 'नया राज्य मॉडल जोड़ें',
    connectedStates: 'संबद्ध राज्य',
    sharedModels: 'साझा कृषि मॉडल',
  },
  en: {
    appName: 'Krishi Saarthi',
    networkTitle: 'Cooperative Agricultural Intelligence Network',
    tagline: 'From satellite intelligence to farmer action.',
    markField: 'Mark Your Field',
    satelliteIntelligence: 'Satellite Intelligence',
    weatherIntelligence: 'Weather Intelligence',
    soilIntelligence: 'Soil Intelligence',
    cropRecommendation: 'Crop Recommendation Engine',
    cropDoctor: 'Crop Disease Diagnosis',
    aiCopilot: 'Krishi Saarthi AI Copilot',
    stateCooperation: 'State Cooperation Network',
    liveTelemetry: 'Live Orbital Telemetry',
    demoMode: 'Verified Demo Data',
    healthyStatus: 'Healthy Vigor',
    moderateStress: 'Moderate Stress',
    degradedStatus: 'Degraded Canopy',
    highRisk: 'HIGH RISK',
    mediumRisk: 'MEDIUM RISK',
    lowRisk: 'LOW RISK',
    rainfallWarning: '62 mm heavy precipitation forecasted in next 72h',
    postponeIrrigation: 'Postpone irrigation and chemical spray',
    suitabilityScore: 'Suitability Score',
    whyThisCrop: 'Why this crop?',
    soilSuitability: 'Soil Suitability',
    rainfallSuitability: 'Rainfall Fit',
    tempSuitability: 'Temperature Fit',
    waterMatch: 'Water Requirement',
    satelliteCondition: 'Satellite Canopy Vigor',
    askQuestionPlaceholder: 'Ask Krishi Saarthi about your field, weather, or crops...',
    send: 'Ask',
    quickQuestions: 'Quick Inquiries',
    q1: 'How is the crop health in my field?',
    q2: 'Should I irrigate within the next 3 days?',
    q3: 'What is the top recommended crop after soybean?',
    diagnoseTitle: 'Upload crop leaf image or select sample preset',
    severity: 'Severity',
    confidence: 'Confidence',
    disclaimer: 'AI prediction based on visual symptoms. Always consult your local KVK or extension officer.',
    switchField: 'Switch Field',
    registerModel: 'Register State Model',
    connectedStates: 'Connected States',
    sharedModels: 'Shared Agricultural Models',
  },
  mr: {
    appName: 'कृषी सारथी',
    networkTitle: 'सहकारी कृषी बुद्धिमत्ता नेटवर्क',
    tagline: 'उपग्रह माहितीवरून शेतकऱ्यांच्या कृतीपर्यंत',
    markField: 'आपले शेत चिन्हांकित करा',
    satelliteIntelligence: 'उपग्रह बुद्धिमत्ता',
    weatherIntelligence: 'हवामान बुद्धिमत्ता',
    soilIntelligence: 'मृदा बुद्धिमत्ता',
    cropRecommendation: 'पीक शिफारस इंजिन',
    cropDoctor: 'पीक रोग निदान',
    aiCopilot: 'कृषी सारथी AI सल्लागार',
    stateCooperation: 'राज्य सहकार्य नेटवर्क',
    liveTelemetry: 'सक्रिय उपग्रह टेलीमेट्री',
    demoMode: 'सत्यापित डेमो डेटा',
    healthyStatus: 'उत्तम आरोग्य',
    moderateStress: 'मध्यम ताण',
    degradedStatus: 'गंभीर घट',
    highRisk: 'उच्च धोका',
    mediumRisk: 'मध्यम धोका',
    lowRisk: 'कमी धोका',
    rainfallWarning: 'पुढील 72 तासांत 62 mm मुसळधार पावसाचा अंदाज',
    postponeIrrigation: 'पाणी देणे आणि औषध फवारणी पुढे ढकला',
    suitabilityScore: 'उपयुक्तता गुण',
    whyThisCrop: 'हे पीक का?',
    soilSuitability: 'मातीची अनुकूलता',
    rainfallSuitability: 'पावसाची अनुकूलता',
    tempSuitability: 'तापमान अनुकूलता',
    waterMatch: 'पाणी आवश्यकता मेळ',
    satelliteCondition: 'उपग्रह स्थिती',
    askQuestionPlaceholder: 'कृषी सारथीला विचारा...',
    send: 'विचारा',
    quickQuestions: 'त्वरित प्रश्न',
    q1: 'माझ्या शेतात पिकाची प्रकृती कशी आहे?',
    q2: 'पुढील ३ दिवसात पाणी द्यावे का?',
    q3: 'सोयाबीन नंतर कोणते पीक योग्य राहील?',
    diagnoseTitle: 'पानाचा फोटो अपलोड करा किंवा नमुना निवडा',
    severity: 'तीव्रता',
    confidence: 'अचूकता',
    disclaimer: 'हे निदान AI अनुमानावर आधारित आहे. स्थानिक कृषी अधिकाऱ्यांचा सल्ला घ्या.',
    switchField: 'शेत बदला',
    registerModel: 'राज्य मॉडेल नोंदवा',
    connectedStates: 'जोडलेली राज्ये',
    sharedModels: 'सामायिक कृषी मॉडेल्स',
  },
  gu: {
    appName: 'કૃષિ સારથિ',
    networkTitle: 'સહકારી કૃષિ ઇન્ટેલિજન્સ નેટવર્ક',
    tagline: 'સેટેલાઇટ ઇન્ટેલિજન્સથી ખેડૂત કાર્યવાહી સુધી',
    markField: 'તમારું ખેતર ચિહ્નિત કરો',
    satelliteIntelligence: 'સેટેલાઇટ ઇન્ટેલિજન્સ',
    weatherIntelligence: 'હવામાન ઇન્ટેલિજન્સ',
    soilIntelligence: 'જમીન ઇન્ટેલિજન્સ',
    cropRecommendation: 'પાક ભલામણ એન્જિન',
    cropDoctor: 'પાક રોગ નિદાન',
    aiCopilot: 'કૃષિ સારથિ AI સહાયક',
    stateCooperation: 'રાજ્ય સહકાર નેટવર્ક',
    liveTelemetry: 'લાઇવ સેટેલાઇટ ટેલિમેટ્રી',
    demoMode: 'ચકાસાયેલ ડેમો ડેટા',
    healthyStatus: 'સ્વસ્થ પાક',
    moderateStress: 'મધ્યમ તાણ',
    degradedStatus: 'નબળી સ્થિતિ',
    highRisk: 'ઉચ્ચ જોખમ',
    mediumRisk: 'મધ્યમ જોખમ',
    lowRisk: 'ઓછું જોખમ',
    rainfallWarning: 'આગામી 72 કલાકમાં 62 mm ભારે વરસાદની આગાહી',
    postponeIrrigation: 'પિયત અને ખાતર આપવાનું મોકૂફ રાખો',
    suitabilityScore: 'અનુકૂળતા સ્કોર',
    whyThisCrop: 'આ પાક કેમ?',
    soilSuitability: 'જમીન અનુકૂળતા',
    rainfallSuitability: 'વરસાદ અનુકૂળતા',
    tempSuitability: 'તાપમાન અનુકૂળતા',
    waterMatch: 'પાણી જરૂરિયાત મેળ',
    satelliteCondition: 'સેટેલાઇટ પાક સ્થિતિ',
    askQuestionPlaceholder: 'કૃષિ સારથિને પૂછો...',
    send: 'પૂછો',
    quickQuestions: 'ઝડપી પ્રશ્નો',
    q1: 'મારા ખેતરમાં પાકની સ્થિતિ કેવી છે?',
    q2: 'શું આગામી 3 દિવસમાં પિયત કરવું જોઈએ?',
    q3: 'કપાસ પછી કયો પાક શ્રેષ્ઠ છે?',
    diagnoseTitle: 'પાંદડાનો ફોટો અપલોડ કરો અથવા નમૂનો પસંદ કરો',
    severity: 'તીવ્રતા',
    confidence: 'વિશ્વાસાર્હતા',
    disclaimer: 'આ નિદાન AI અનુમાન પર આધારિત છે. સ્થાનિક KVK ની સલાહ લો.',
    switchField: 'ખેતર બદલો',
    registerModel: 'રાજ્ય મોડેલ નોંધાવો',
    connectedStates: 'જોડાયેલા રાજ્યો',
    sharedModels: 'શેર કરેલ મોડેલ્સ',
  },
  te: {
    appName: 'కృషి సారథి',
    networkTitle: 'సహకార వ్యవసాయ ఇంటెలిజెన్స్ నెట్‌వర్క్',
    tagline: 'ఉపగ్రహ సమాచారం నుండి రైతు కార్యాచరణ వరకు',
    markField: 'మీ పొలాన్ని గుర్తించండి',
    satelliteIntelligence: 'ఉపగ్రహ ఇంటెలిజెన్స్',
    weatherIntelligence: 'వాతావరణ ఇంటెలిజెన్స్',
    soilIntelligence: 'నేల ఇంటెలిజెన్స్',
    cropRecommendation: 'పంట సిఫార్సు ఇంజిన్',
    cropDoctor: 'పంట వ్యాధి నిర్ధారణ',
    aiCopilot: 'కృషి సారథి AI సహాయకుడు',
    stateCooperation: 'రాష్ట్ర సహకార నెట్‌వర్క్',
    liveTelemetry: 'ప్రత్యక్ష ఉపగ్రహ టెలిమెట్రీ',
    demoMode: 'ధృవీకరించబడిన డెమో డేటా',
    healthyStatus: 'ఆరోగ్యకరమైన పంట',
    moderateStress: 'మితమైన ఒత్తిడి',
    degradedStatus: 'తీవ్ర క్షీణత',
    highRisk: 'అధిక ప్రమాదం',
    mediumRisk: 'మధ్యస్థ ప్రమాదం',
    lowRisk: 'తక్కువ ప్రమాదం',
    rainfallWarning: 'రాబోయే 72 గంటల్లో 62 mm భారీ వర్షపాతం హెచ్చరిక',
    postponeIrrigation: 'నీటిపారుదల మరియు మందుల పిచికారీని వాయిదా వేయండి',
    suitabilityScore: 'అనుకూలత స్కోరు',
    whyThisCrop: 'ఈ పంట ఎందుకు?',
    soilSuitability: 'నేల అనుకూలత',
    rainfallSuitability: 'వర్షపాతం అనుకూలత',
    tempSuitability: 'ఉష్ణోగ్రత అనుకూలత',
    waterMatch: 'నీటి అవసరం సరిపోలిక',
    satelliteCondition: 'ఉపగ్రహ పంట స్థితి',
    askQuestionPlaceholder: 'కృషి సారథిని అడగండి...',
    send: 'అడగండి',
    quickQuestions: 'శీఘ్ర ప్రశ్నలు',
    q1: 'నా పొలంలో పంట ఆరోగ్యం ఎలా ఉంది?',
    q2: 'రాబోయే 3 రోజుల్లో నీరు పెట్టాలా?',
    q3: 'సోయాబీన్ తర్వాత ఏ పంట అనుకూలం?',
    diagnoseTitle: 'ఆకు చిత్రాన్ని అప్‌లోడ్ చేయండి లేదా నమూనాను ఎంచుకోండి',
    severity: 'తీవ్రత',
    confidence: 'ఖచ్చితత్వం',
    disclaimer: 'ఈ రోగనిర్ధారణ AI అంచనాపై ఆధారపడి ఉంటుంది. స్థానిక KVK ని సంప్రదించండి.',
    switchField: 'పొలాన్ని మార్చండి',
    registerModel: 'రాష్ట్ర మోడల్ నమోదు చేయండి',
    connectedStates: 'కనెక్ట్ చేయబడిన రాష్ట్రాలు',
    sharedModels: 'భాగస్వామ్య మోడల్స్',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'hi',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('krishi_saarthi_lang');
    return (saved as LanguageCode) || 'hi';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('krishi_saarthi_lang', lang);
  };

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
